# -*- coding: utf-8 -*-
"""yolov5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LwoUqIKmFPt2yPA4TE8uAfI7zDyf1br6
"""

import cv2 
import numpy as np

!git clone https://github.com/ultralytics/yolov5.git

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov5/

!pip install -r requirements.txt

!wget https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5s.pt

!python train.py --img 416 --batch 8 --epochs 100 --data /content/drive/MyDrive/cement_bag/dataset.yaml --weights /content/yolov5/yolov5s.pt --nosave --cache

!python train.py --img 416 --batch 8 --epochs 200 --data /content/drive/MyDrive/cement_bag/dataset.yaml --weights /content/yolov5/runs/train/exp/weights/last.pt

